spring.application.name=mercury-market
server.port=8080
server.shutdown=graceful
# define o profile padrão (mariadb)
spring.profiles.active=h2
api.security.secret=natosoreidosexofuradordocaralhotaligadotwitter
api.security.expiration=86400000
