# -------------------------
# Aplicação
# -------------------------
spring.application.name=mercury-market
server.port= 8080
server.shutdown=graceful
# -------------------------
# Conexão MariaDB
# -------------------------
spring.datasource.url=jdbc:mariadb://localhost:3306/mercury_market
spring.datasource.username=usuario
spring.datasource.password=senha123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# -------------------------
# Banco H2 (opcional, memória)
# -------------------------
# Para usar H2 no lugar do MariaDB, comente MariaDB acima e descomente:
# spring.datasource.url=jdbc:h2:mem:mercury_market_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
