spring.application.name=mercury-market
server.port=8041
# Banco H2 (modo memória)
spring.datasource.url=jdbc:h2:mem:mercury_market_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criação automática do schema
spring.jpa.hibernate.ddl-auto=update

# Console web pra inspecionar o banco
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
