# Configuração explícita para o perfil 'h2'
spring.datasource.url=jdbc:h2:mem:mercury_market_db
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# ? CORREÇÃO REFORÇADA: EXCLUI a autoconfiguração do DataSource.
# Isso impede que o Spring procure automaticamente por drivers no classpath (como o MariaDB)
# e força-o a usar APENAS as propriedades que definimos acima.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Ativar console H2
spring.h2.console.enabled=true
